name: Manual workflow

on:
    workflow_dispatch:
    schedule:
        - cron: "0 12 * * *"

jobs:
    greet:
        runs-on: ubuntu-latest

        steps:
            - name: Make Req
              uses: Satak/webrequest-action@v1.2.3
              with:
                  url: "https://birthdaysbot-api.herokuapp.com/birthdays/send"
                  method: GET
                  headers: '{"api-key": "${{ secrets.API_KEY }}"}'
