# This is a basic workflow to help you get started with Actions

name: Send Happy Birthdays

# Controls when the workflow will run
on:
  # Triggers the workflow every day at 09:00
  schedule:
    - cron: "44 1 * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  send:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: HTTP Request Action
        id: myReq
        uses: fjogeleit/http-request-action@v1.9.1
        with:
          # Web request URL endpoint
          url: "https://birthdaysbot-api.herokuapp.com/birthdays/send"
          method: GET
          headers: '{"api-key": "${{ secrets.API_KEY }}"}'
      - name: Show Response
        run: echo ${{ steps.myReq.outputs.response }}
